#!/bin/bash

set -o pipefail

#set -x # For development purposes, remove later

function usage() {
    echo -e "\
    Usage: ./`basename $0` <routine> <config>
    
    Where: <routine> is one of:
        1a | Split_by_Family
        1b | Parental_Fill_In
        2 | Mendel_Checking
        3 | Make_Rqtl_Files
        4a | Data_Diagnostics
        4b | Crossover_Phenotyping
        4c | Crossovers_Summary_Plots
        5a | GEMMA_File_Prep
        5b | GEMMA_Analysis
    
    And: <config> is the full file path to the configuration file

    Routines can be specified by number (e.g., 1a) or by name (e.g., Split_by_Family). Some routines are optional, please refer to the documentation on which ones are optional.
    " >&2
    exit 1
}

export -f usage

# Where is 'crossing_over' located?
SCRIPT=$(realpath "$0") # Trace back the symbolic link to find the actual location
CROSSING_OVER=$(dirname "${SCRIPT}")

# Check if we have less than two arguments
#   If yes, display usage message
if [[ "$#" -lt 1 ]]; then usage; fi

# Which routine are we running?
ROUTINE="$1"
# Where is our config file?
CONFIG=$(realpath "$2")

# If the config exists, source it to provide parameters and software
if [[ -f "${CONFIG}" ]]
then
    source "${CONFIG}"
else
    echo "Please specify a valid config file." >&2
    exit 1 # Exit with non-zero exit status
fi

# After loading config, make sure output directory exists
mkdir -p "${OUT_DIR}"
if ! [[ -w "${OUT_DIR}" ]]
then
    echo "You don't have write permissions for the output directory ${OUT_DIR}, exiting..." >&2
    exit 1
fi

# Run crossing_over
case "${ROUTINE}" in
    1a | Split_by_Family)
        "${CROSSING_OVER}"/scripts/data_handling/split_by_family.sh \
            "${PED_FILE}" \
            "${OUT_DIR}" \
            "${CROSSING_OVER}"
    ;;
    1b | Parental_Fill_In)
        # Requires GNU parallel, add check for dependency
        "${CROSSING_OVER}"/scripts/data_handling/PED_parental_fill-in.sh \
            "${PED_LIST}" \
            "${OUT_DIR}" \
            "${CROSSING_OVER}"
    ;;
    2 | Mendel_Checking)
        echo "Will be available in the near future, currently under development..."
    ;;
    3 | Make_Rqtl_Files)
        # Convert Plink 1.9 files to R/qtl2 input file format
        "${CROSSING_OVER}"/scripts/data_handling/Plink2Rqtl2_format.sh \
            "${PED_DIR}" \
            "${MAP_FILE}" \
            "${LOOKUP_TABLE}" \
            "${OUT_DIR}" \
            "${CROSSING_OVER}" \
            "${P2RQTL2_SUFFIX}"
        # Generate R/qtl2 control files (i.e., .yaml files)
        "${CROSSING_OVER}"/scripts/data_handling/make_control_files.sh \
            "${QTL_INPUTS_DIR}" \
            "${CROSSING_OVER}" \
            "${CROSSTYPE}"
    ;;
    4a | Data_Diagnostics)
        echo "Run data diagnostic evaluation prior to generating crossover phenotypes..."
        echo "Please look closely at the summary plots and resolve any data issues before proceeding to next step."
        "${CROSSING_OVER}"/scripts/data_handling/data_diagnostics_rqtl.sh \
            "${YAML_PREFIX}" \
            "${PROGENY_GENO_LIST}" \
            "${FOUNDER_GENO_LIST}" \
            "${GMAP_LIST}" \
            "${PMAP_LIST}" \
            "${CROSSTYPE}" \
            "${OUT_DIR}" \
            "${CROSSING_OVER}"
    ;;
    4b | Crossover_Phenotyping)
        echo "Generating crossover phenotypes..."
        "${CROSSING_OVER}"/scripts/crossovers/rqtl2_xo_counts.sh \
            "${QTL_INPUTS_DIR}" \
            "${PERICENTROMERES}" \
            "${OUT_DIR}" \
            "${CROSSING_OVER}"
    ;;
    4c | Crossovers_Summary_Plots)
        # Generate summary plots
        echo "Generating crossover summary plots..."
        "${CROSSING_OVER}"/scripts/crossovers/xo_count_summary_plotting.sh \
            "${XO_DATA_DIR}" \
            "${OUT_DIR}" \
            "${PEDIGREE}" \
            "${PLOT_GROUPINGS}" \
            "${CROSSING_OVER}"
    ;;
    5a | GEMMA_File_Prep)
        # GEMMA: Genome-wide Efficient Mixed Model Association
        # Combine phenotypes with PLINK files
        "${CROSSING_OVER}"/scripts/Gemma/combine_pheno_and_plink.sh \
            "${XO_DATA_DIR}" \
            "${FINAL_SPLIT_PED_DIR}" \
            "${FOUNDERS_PED}" \
            "${MAP_FILE}" \
            "${OUT_DIR}" \
            "${CROSSING_OVER}"
    ;;
    5b | GEMMA_Analysis)
        # Run GEMMA analysis
        "${CROSSING_OVER}"/scripts/Gemma/gemma_analysis.sh \
            "${PED_FILE}" \
            "${OUT_DIR}" \
            "${SCRIPT_DIR}" \
            "${TEMP}"
    ;;
    * )
    usage
    ;;
esac